kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30001 #activemq svc
    hostPort: 30071
  - containerPort: 30002 #activemq svc
    hostPort: 30072
  - containerPort: 30003 #activemq svc
    hostPort: 30073
  - containerPort: 30004 #activemq svc
    hostPort: 30074
  - containerPort: 30080 #alfresco svc
    hostPort: 30080
  - containerPort: 30090 #content-app svc
    hostPort: 30090
  - containerPort: 30100 #postgres svc
    hostPort: 30100
  - containerPort: 30110 #proxy svc
    hostPort: 30110
  - containerPort: 30120 #share svc
    hostPort: 30120
  - containerPort: 30130 #solr6 svc
    hostPort: 30130
  - containerPort: 30140 #transform-core-aio svc
    hostPort: 30140
- role: worker
- role: worker
