apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  type: LoadBalancer
  ports:
    - name: "port-8161"
      port: 8161
      targetPort: 8161
      nodePort: 30001
    - name: "port-5672"
      port: 5672
      targetPort: 5672
      nodePort: 30002
    - name: "port-61616"
      port: 61616
      targetPort: 61616
      nodePort: 30003
    - name: "port-61613"
      port: 61613
      targetPort: 61613
      nodePort: 30004
  selector:
    io.kompose.service: activemq
