apiVersion: apps/v1
kind: Deployment
metadata:
  name: alfresco
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alfresco
  template:
    metadata:
      labels:
        io.kompose.network/pepe-default: "true"
        io.kompose.service: alfresco
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: "-Ddb.driver=org.postgresql.Driver -Ddb.username=alfresco -Ddb.password=alfresco -Ddb.url=jdbc:postgresql://postgres:5432/alfresco -Dsolr.host=solr6 -Dsolr.port=8983 -Dsolr.http.connection.timeout=1000 -Dsolr.secureComms=secret -Dsolr.sharedSecret=secret -Dsolr.base.url=/solr -Dindex.subsystem.name=solr6 -Dshare.host=localhost -Dshare.port=30120 -Dalfresco.host=localhost -Dalfresco.port=8080 -Dcsrf.filter.enabled=false -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\" -Ddeployment.method=DOCKER_COMPOSE -DlocalTransform.core-aio.url=http://transform-core-aio:8090/ -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dencryption.keystore.type=JCEKS -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding -Dencryption.keyAlgorithm=DESede -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore -Dmetadata-keystore.password=mp6yc0UD9e -Dmetadata-keystore.aliases=metadata -Dmetadata-keystore.metadata.password=oKIWzVdEdA -Dmetadata-keystore.metadata.algorithm=DESede"
          image: docker.io/alfresco/alfresco-content-repository-community:7.4.0.1
          name: alfresco
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1992294400"
      restartPolicy: Always
