apiVersion: v1
kind: Service
metadata:
  name: alfresco
spec:
  type: LoadBalancer
  ports:
    - name: "port-8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: alfresco
