apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  template:
    metadata:
      labels:
        io.kompose.network/pepe-default: "true"
        io.kompose.service: postgres
    spec:
      volumes:
        - name: my-persistent-volume
          persistentVolumeClaim:
            claimName: my-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres:14.4
          ports:
            - containerPort: 5432
          args:
            - postgres
            - -c
            - max_connections=300
            - -c
            - log_min_messages=LOG
          env:
            - name: POSTGRES_DB
              value: alfresco
            - name: POSTGRES_PASSWORD
              value: alfresco
            - name: POSTGRES_USER
              value: alfresco
          resources:
            limits:
              memory: "536870912"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: my-persistent-volume
