apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: LoadBalancer
  ports:
    - name: port-5432
      port: 5432
      targetPort: 5432
      nodePort: 30100
  selector:
    io.kompose.service: postgres
