apiVersion: v1
kind: Service
metadata:
  name: share
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30120
  selector:
    io.kompose.service: share
