apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: solr6
  name: solr6
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr6
  template:
    metadata:
     labels:
        io.kompose.network/pepe-default: "true"
        io.kompose.service: solr6
    spec:
      containers:
        - env:
            - name: SOLR_ALFRESCO_HOST
              value: alfresco
            - name: SOLR_ALFRESCO_PORT
              value: "8080"
            - name: SOLR_CREATE_ALFRESCO_DEFAULTS
              value: alfresco,archive
            - name: SOLR_SOLR_HOST
              value: solr6
            - name: SOLR_SOLR_PORT
              value: "8983"
          image: docker.io/alfresco/alfresco-search-services:2.0.7
          name: solr6
          ports:
            - containerPort: 8983
          resources:
            limits:
              memory: "2147483648"
      restartPolicy: Always
