apiVersion: v1
kind: Service
metadata:
  name: content-app
spec:
  type: LoadBalancer
  ports:
    - name: "port-8080"
      port: 8080
      targetPort: 8080
      nodePort: 30090
  selector:
    io.kompose.service: content-app
