apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: solr6
  name: solr6
spec:
  type: LoadBalancer
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8983
      nodePort: 30130
  selector:
    io.kompose.service: solr6
